"""
Event Schemas (OCSF-aligned)
=============================
Defines the canonical event types flowing through the pipeline.
BlackStarSIEM v2 adopts the Open Cybersecurity Schema Framework (OCSF)
field vocabulary while remaining serialisable to plain Python dicts /
JSON for easy downstream use.

Reference: https://schema.ocsf.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import IntEnum
from typing import Any, Dict, Optional
import uuid


# ---------------------------------------------------------------------------
# OCSF class IDs (subset used by this SIEM)
# ---------------------------------------------------------------------------
class EventClass(IntEnum):
    NETWORK_ACTIVITY = 4001
    AUTHENTICATION = 3002
    FILE_ACTIVITY = 1001
    PROCESS_ACTIVITY = 1007
    SECURITY_FINDING = 2001   # generated by rules engine


class Severity(IntEnum):
    INFORMATIONAL = 1
    LOW = 2
    MEDIUM = 3
    HIGH = 4
    CRITICAL = 5

    def label(self) -> str:
        return self.name.lower()


# ---------------------------------------------------------------------------
# Common sub-objects
# ---------------------------------------------------------------------------
@dataclass
class NetworkEndpoint:
    ip: str
    port: int = 0
    hostname: str = ""
    domain: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class UserInfo:
    name: str
    uid: str = ""
    is_admin: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ProcessInfo:
    name: str
    pid: int = 0
    cmd_line: str = ""
    parent_name: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class FileInfo:
    path: str
    name: str = ""
    type: str = ""
    size: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Base security event
# ---------------------------------------------------------------------------
@dataclass
class SecurityEvent:
    """Base OCSF-aligned security event."""

    # Core OCSF fields
    class_uid: int
    category_uid: int
    activity_id: int
    severity_id: int
    status: str                      # "success" | "failure" | "unknown"
    message: str

    # Identifiers
    event_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    time: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    # Context
    src_endpoint: Optional[NetworkEndpoint] = None
    dst_endpoint: Optional[NetworkEndpoint] = None
    user: Optional[UserInfo] = None
    process: Optional[ProcessInfo] = None
    file: Optional[FileInfo] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    # Ingest provenance (filled by consumer)
    kafka_topic: str = ""
    kafka_partition: int = 0
    kafka_offset: int = -1

    def to_dict(self) -> Dict[str, Any]:
        """Flatten to a JSON-serialisable dict (for Kafka / Iceberg)."""
        d: Dict[str, Any] = {
            "event_id": self.event_id,
            "time": self.time,
            "class_uid": self.class_uid,
            "category_uid": self.category_uid,
            "activity_id": self.activity_id,
            "severity_id": self.severity_id,
            "severity": Severity(self.severity_id).label(),
            "status": self.status,
            "message": self.message,
            "kafka_topic": self.kafka_topic,
            "kafka_partition": self.kafka_partition,
            "kafka_offset": self.kafka_offset,
        }
        if self.src_endpoint:
            d["src_ip"] = self.src_endpoint.ip
            d["src_port"] = self.src_endpoint.port
            d["src_hostname"] = self.src_endpoint.hostname
        if self.dst_endpoint:
            d["dst_ip"] = self.dst_endpoint.ip
            d["dst_port"] = self.dst_endpoint.port
            d["dst_hostname"] = self.dst_endpoint.hostname
        if self.user:
            d["user_name"] = self.user.name
            d["user_uid"] = self.user.uid
            d["user_is_admin"] = self.user.is_admin
        if self.process:
            d["proc_name"] = self.process.name
            d["proc_pid"] = self.process.pid
            d["proc_cmd_line"] = self.process.cmd_line
            d["proc_parent"] = self.process.parent_name
        if self.file:
            d["file_path"] = self.file.path
            d["file_name"] = self.file.name
            d["file_type"] = self.file.type
        for k, v in self.metadata.items():
            d[f"meta_{k}"] = str(v)
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "SecurityEvent":
        src = NetworkEndpoint(
            ip=d.get("src_ip", ""),
            port=d.get("src_port", 0),
            hostname=d.get("src_hostname", ""),
        ) if d.get("src_ip") else None
        dst = NetworkEndpoint(
            ip=d.get("dst_ip", ""),
            port=d.get("dst_port", 0),
            hostname=d.get("dst_hostname", ""),
        ) if d.get("dst_ip") else None
        user = UserInfo(
            name=d.get("user_name", ""),
            uid=d.get("user_uid", ""),
            is_admin=d.get("user_is_admin", False),
        ) if d.get("user_name") else None
        process = ProcessInfo(
            name=d.get("proc_name", ""),
            pid=d.get("proc_pid", 0),
            cmd_line=d.get("proc_cmd_line", ""),
            parent_name=d.get("proc_parent", ""),
        ) if d.get("proc_name") else None
        file = FileInfo(
            path=d.get("file_path", ""),
            name=d.get("file_name", ""),
            type=d.get("file_type", ""),
        ) if d.get("file_path") else None
        return cls(
            event_id=d.get("event_id", str(uuid.uuid4())),
            time=d.get("time", datetime.now(timezone.utc).isoformat()),
            class_uid=d.get("class_uid", EventClass.NETWORK_ACTIVITY),
            category_uid=d.get("category_uid", 4),
            activity_id=d.get("activity_id", 1),
            severity_id=d.get("severity_id", Severity.INFORMATIONAL),
            status=d.get("status", "unknown"),
            message=d.get("message", ""),
            src_endpoint=src,
            dst_endpoint=dst,
            user=user,
            process=process,
            file=file,
            kafka_topic=d.get("kafka_topic", ""),
            kafka_partition=d.get("kafka_partition", 0),
            kafka_offset=d.get("kafka_offset", -1),
        )
